# Generated by Django 4.1.6 on 2023-02-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='pokemons',
            field=models.ManyToManyField(to='main_app.pokemon'),
        ),
    ]
