# Generated by Django 4.1.6 on 2023-02-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='pokemon',
        ),
    ]
